//! The bytes served by the binary are also the release's verified Web contract.
pub(crate) const HTML: &str = include_str!("../../../web/dist/index.html");
pub(crate) const SCRIPT: &[u8] = include_bytes!("../../../web/dist/assets/admin.js");
pub(crate) const STYLES: &[u8] = include_bytes!("../../../web/dist/assets/admin.css");
// Exact reviewed current asset inventory; no runtime directory discovery.
pub(crate) const RELEASE_FILES: &[(&str, &[u8])] = &[
    (
        "share/web/assets/CJK-LICENSE.txt",
        include_bytes!("../../../web/dist/assets/CJK-LICENSE.txt"),
    ),
    (
        "share/web/assets/MapleMonoBootstrap-Regular.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoBootstrap-Regular.woff2"),
    ),
    (
        "share/web/assets/MapleMonoBootstrap-Bold.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoBootstrap-Bold.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNormalNL-Regular.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNormalNL-Regular.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNormalNL-Bold.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNormalNL-Bold.woff2"),
    ),
    (
        "share/web/assets/MapleMono-OFL.txt",
        include_bytes!("../../../web/dist/assets/MapleMono-OFL.txt"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-4D4-50CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-4D4-50CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-50CF-52CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-50CF-52CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-52CF-54CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-52CF-54CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-54CF-56CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-54CF-56CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-56CF-58CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-56CF-58CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-58CF-5ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-58CF-5ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-5ACF-5CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-5ACF-5CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-5CCF-5ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-5CCF-5ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-5ECF-60CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-5ECF-60CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-60CF-62CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-60CF-62CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-62CF-64CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-62CF-64CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-64CF-66CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-64CF-66CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-66CF-68CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-66CF-68CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-68CF-6ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-68CF-6ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-6ACF-6CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-6ACF-6CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-6CCF-6ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-6CCF-6ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-6ECF-70CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-6ECF-70CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-70CF-72CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-70CF-72CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-72CF-74CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-72CF-74CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-74CF-76CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-74CF-76CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-76CF-78CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-76CF-78CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-78CF-7ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-78CF-7ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-7ACF-7CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-7ACF-7CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-7CCF-7ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-7CCF-7ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-7ECF-80CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-7ECF-80CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-80CF-82CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-80CF-82CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-82CF-84CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-82CF-84CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-84CF-86CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-84CF-86CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-86CF-88CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-86CF-88CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-88CF-8ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-88CF-8ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-8ACF-8CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-8ACF-8CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-8CCF-8ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-8CCF-8ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-8ECF-90CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-8ECF-90CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-90CF-92CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-90CF-92CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-92CF-94CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-92CF-94CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-94CF-96CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-94CF-96CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-96CF-98CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-96CF-98CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-98CF-9ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-98CF-9ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-9ACF-9CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-9ACF-9CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-9CCF-9E67.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-9CCF-9E67.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Bold-9E68-FFEE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Bold-9E68-FFEE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-4D4-50CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-4D4-50CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-50CF-52CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-50CF-52CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-52CF-54CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-52CF-54CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-54CF-56CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-54CF-56CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-56CF-58CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-56CF-58CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-58CF-5ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-58CF-5ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-5ACF-5CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-5ACF-5CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-5CCF-5ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-5CCF-5ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-5ECF-60CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-5ECF-60CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-60CF-62CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-60CF-62CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-62CF-64CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-62CF-64CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-64CF-66CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-64CF-66CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-66CF-68CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-66CF-68CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-68CF-6ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-68CF-6ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-6ACF-6CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-6ACF-6CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-6CCF-6ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-6CCF-6ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-6ECF-70CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-6ECF-70CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-70CF-72CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-70CF-72CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-72CF-74CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-72CF-74CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-74CF-76CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-74CF-76CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-76CF-78CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-76CF-78CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-78CF-7ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-78CF-7ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-7ACF-7CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-7ACF-7CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-7CCF-7ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-7CCF-7ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-7ECF-80CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-7ECF-80CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-80CF-82CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-80CF-82CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-82CF-84CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-82CF-84CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-84CF-86CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-84CF-86CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-86CF-88CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-86CF-88CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-88CF-8ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-88CF-8ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-8ACF-8CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-8ACF-8CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-8CCF-8ECE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-8CCF-8ECE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-8ECF-90CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-8ECF-90CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-90CF-92CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-90CF-92CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-92CF-94CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-92CF-94CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-94CF-96CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-94CF-96CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-96CF-98CE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-96CF-98CE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-98CF-9ACE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-98CF-9ACE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-9ACF-9CCE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-9ACF-9CCE.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-9CCF-9E67.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-9CCF-9E67.woff2"),
    ),
    (
        "share/web/assets/MapleMonoNL-CN-Regular-9E68-FFEE.woff2",
        include_bytes!("../../../web/dist/assets/MapleMonoNL-CN-Regular-9E68-FFEE.woff2"),
    ),
    ("share/web/assets/admin.css", STYLES),
    ("share/web/assets/admin.js", SCRIPT),
    ("share/web/index.html", HTML.as_bytes()),
];
